plugins {
    id 'groovy'
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.140'
}

// Apply the internal helper tasks
apply from: 'gradle/internal.gradle'

group = 'UNDEFINED'
version = project.version

repositories {
    mavenCentral()
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = '26.1.2.78'
    runs {
        client {
            client()
        }

        server {
            server()
            programArgument '--nogui'
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'terminal.ansi', 'true'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }
}

tasks.named('runClient') {
    dependsOn tasks.named('deployBundle')
}

dependencies {
    implementation "org.apache.groovy:groovy:5.0.4"
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'


}

test {
    useJUnitPlatform()
}