plugins {
    id 'groovy'
    id 'java-library'
	id 'net.neoforged.moddev'
}

// Apply the internal helper tasks
apply from: 'gradle/internal.gradle'

version = project.version

repositories {
	mavenLocal()
	gradlePluginPortal()
	mavenCentral()
	maven {
		name "Neoforge"
		url "https://maven.neoforged.net/releases"
	}
	maven {
		name "Latvian"
		url "https://maven.latvian.dev/releases"
	}
	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
	}
	maven {
		name = "Jared's maven"
		url = "https://maven.blamejared.com/"
	}
	maven {
		name = "ModMaven"
		url = "https://modmaven.dev"
	}
	maven() {
		name = "RyanHCode Maven"
		url = "https://maven.ryanhcode.dev/releases"
	}
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
	version = neo_version
}

dependencies {
    implementation "org.apache.groovy:groovy:5.0.4"
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	implementation(project(':26.1'))
}

test {
    useJUnitPlatform()
}